### ISSUE TITLE
Mini USB retrofit

### ISSUE THREAD

**Issue by ctjameson** [combs/USBC6P#1]
Do you think it’d be possible to use these for retrofitting a mini USB port that is only used for charging?

**Comment by combs** [comment]
Not without a bunch of fussy work. It doesn't really have the pins in the same or similar places, and you need to add 5.1k resistors to two places for the port to register with USB 3 chargers. Sorry, I wish it worked for this!

**Comment by ctjameson** [comment]
Well darn. Guess I’ll just have to deal with the antiquated charging.
